export enum RedditActionTypes {
    // REDDIT API
    SERVICE_FETCHING = "REDDIT_SERVICE_FETCHING",
    SERVICE_ERROR = "REDDIT_SERVICE_ERROR",
    // REDDIT DATA
    FETCH_DATA = "REDDIT_FETCH_DATA",
    DISMISS_POST = "REDDIT_DISMISS_POST",
    DISMISS_ALL_POSTS = "REDDIT_DISMISS_ALL_POSTS",
    READ_POST = "REDDIT_READ_POST",
    // UI
    TOGGLE_MENU = "REDDIT_TOGGLE_MENU",
}
