export enum RedditActionTypes {
    FETCH_DATA = "REDDIT_FETCH_DATA",
    DISMISS_POST = "REDDIT_DISMISS_POST",
    DISMISS_ALL_POSTS = "REDDIT_DISMISS_ALL_POSTS",
    READ_POST = "REDDIT_READ_POST",
}
